name: esc_pos_bluetooth
description: The library allows to print receipts using an ESC/POS thermal Bluetooth printer.
version: 0.4.1
homepage: https://github.com/andrey-ushakov/esc_pos_bluetooth

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.0
  esc_pos_utils: ^1.1.0
  # esc_pos_utils:
  # path: ../esc_pos_utils
  # flutter_bluetooth_basic: ^0.1.7
  flutter_bluetooth_basic:
    git:
      url: https://github.com/ttyniwa/flutter_bluetooth_basic 
      ref: 65e7b98b06c2fdc8da5dc1ed3b50548496f69b87

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
